name: prometheus-((environment))

releases:
- {name: prometheus, version: latest}
- {name: oauth2-proxy, version: latest}

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-600000
  update_watch_time: 1000-600000
  serial: false

instance_groups:
- name: alertmanager
  instances: 1
  vm_type: ((environment))-prometheus-small
  persistent_disk_type: ((environment))-prometheus-small
  stemcell: default
  azs: ((azs))
  networks:
  - name: ((environment))-monitoring
  jobs:
  - name: alertmanager
    release: prometheus
    properties:
      alertmanager:
        data:
          retention: 720h
        route:
          receiver: notifications
          group_by: ['alertname', 'cluster', 'service']
        receivers:
        - name: notifications
          pagerduty_configs:
          - service_key: ((pagerduty-key))
          email_configs:
          - to: ((cg-email-address))
        smtp:
          from: no-reply@cloud.gov
          smarthost: ((smtp-hostname))
          auth_username: ((smtp-username))
          auth_password: ((smtp-password))
          require_tls: true

- name: prometheus
  instances: 1
  vm_type: ((environment))-prometheus-large
  persistent_disk_type: ((environment))-prometheus-large
  stemcell: default
  azs: ((azs))
  networks:
  - name: ((environment))-monitoring
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: prometheus2
    release: prometheus
    properties:
      prometheus:
        storage:
          tsdb:
            retention: 30d
        web:
          external_url: https://prometheus.((domain))
        rule_files:
        - /var/vcap/jobs/bosh_alerts/*.alerts.yml
        - /var/vcap/jobs/cloudfoundry_alerts/*.alerts.yml
        - /var/vcap/jobs/kubernetes_alerts/*.alerts.yml
        - /var/vcap/jobs/elasticsearch_alerts/*.alerts.yml
        - /var/vcap/jobs/concourse_alerts/*.alerts.yml
        - /var/vcap/jobs/prometheus_alerts/*.alerts.yml
        scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets:
            - localhost:9090
        - job_name: pushgateway
          honor_labels: true
          static_configs:
          - targets:
            - localhost:9091
        - job_name: bosh
          scrape_interval: 1m
          scrape_timeout: 1m
          static_configs:
          - targets:
            - localhost:9190
        - job_name: firehose
          static_configs:
          - targets:
            - localhost:9186
        - job_name: kube_state_metrics_exporter
          static_configs:
          - targets:
            - localhost:9188
        - job_name: elasticsearch_exporter
          file_sd_configs:
          - files:
            - /var/vcap/store/bosh_exporter/bosh_target_groups.json
          relabel_configs:
          - source_labels: [__meta_bosh_job_process_name]
            regex: elasticsearch_exporter
            action: keep
          - source_labels: [__address__]
            regex: "(.*)"
            target_label: __address__
            replacement: "${1}:9114"
        - job_name: blackbox
          metrics_path: /probe
          params:
            module:
            - http
          static_configs:
          - targets: ((blackbox-targets))
          relabel_configs:
          - source_labels: [__address__]
            regex: (.*)
            target_label: __param_target
            replacement: ${1}
          - source_labels: [__param_target]
            regex: (.*)
            target_label: instance
            replacement: ${1}
          - source_labels: []
            regex: .*
            target_label: __address__
            replacement: localhost:9115
        - job_name: node
          file_sd_configs:
          - files:
            - /var/vcap/store/bosh_exporter/bosh_target_groups.json
          relabel_configs:
          - source_labels: [__meta_bosh_job_process_name]
            regex: node_exporter
            action: keep
          - source_labels: [__address__]
            regex: "(.*)"
            target_label: __address__
            replacement: "${1}:9100"
  - name: pushgateway
    release: prometheus
  - name: bosh_exporter
    release: prometheus
    properties:
      bosh_exporter:
        bosh:
          url: ((bosh-url))
          ca_cert: ((bosh-ca-cert))
          uaa:
            url: ((bosh-url)):8443
            client_id: ((bosh-client-id))
            client_secret: ((bosh-client-secret))
        metrics:
          environment: ((environment))
  - name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        uaa:
          url: https://login.((domain))
          client_id: ((firehose-client-id))
          client_secret: ((firehose-client-secret))
        doppler:
          url: wss://doppler.((domain)):443
          subscription_id: prometheus
        metrics:
          environment: ((environment))
  - name: kube_state_metrics_exporter
    release: prometheus
    properties:
      kube_state_metrics_exporter:
        apiserver: ((kubernetes-apiserver-url))
        kubeconfig: ((kubernetes-config))
  - name: blackbox_exporter
    release: prometheus
    properties:
      blackbox_exporter:
        config:
          modules:
            http:
              prober: http
              timeout: 5s
              http:
                preferred_ip_protocol: ip4
  - name: bosh_alerts
    release: prometheus
    properties:
      bosh_alerts:
        job_ephemeral_disk_full:
          threshold: 75
          evaluation_time: 10m
        job_ephemeral_persistent_disk_full:
          threshold: 75
          evaluation_time: 10m
        job_persistent_disk_full:
          threshold: 75
          evaluation_time: 10m
        job_predict_persistent_disk_full:
          threshold: 75
          evaluation_time: 10m
  - name: cloudfoundry_alerts
    release: prometheus
  - name: kubernetes_alerts
    release: prometheus
  - name: elasticsearch_alerts
    release: prometheus
  - name: concourse_alerts
    release: prometheus
  - name: prometheus_alerts
    release: prometheus

- name: grafana
  instances: 1
  vm_type: ((environment))-prometheus-small
  persistent_disk_type: ((environment))-prometheus-small
  stemcell: default
  azs: ((azs))
  networks:
  - name: ((environment))-monitoring
  jobs:
  - name: grafana
    release: prometheus
    properties:
      grafana:
        server:
          root_url: https://grafana.((domain))
        security:
          admin_password: ((grafana-admin-password))
        session:
          cookie_secure: "true"
        auth:
          anonymous:
            enabled: true
            org_role: Admin
          basic:
            enabled: false
        dashboards:
          json:
            enabled: true
        prometheus:
          use_external_url: false
          dashboard_files:
          - /var/vcap/jobs/bosh_dashboards/*.json
          - /var/vcap/jobs/system_dashboards/*.json
          - /var/vcap/jobs/cloudfoundry_dashboards/*.json
          - /var/vcap/jobs/kubernetes_dashboards/*.json
          - /var/vcap/jobs/probe_dashboards/*.json
          - /var/vcap/jobs/elasticsearch_dashboards/*.json
          - /var/vcap/jobs/concourse_dashboards/*.json
          - /var/vcap/jobs/prometheus_dashboards/*.json
  - name: bosh_dashboards
    release: prometheus
  - name: system_dashboards
    release: prometheus
  - name: cloudfoundry_dashboards
    release: prometheus
  - name: kubernetes_dashboards
    release: prometheus
  - name: probe_dashboards
    release: prometheus
  - name: elasticsearch_dashboards
    release: prometheus
  - name: concourse_dashboards
    release: prometheus
  - name: prometheus_dashboards
    release: prometheus

- name: nginx
  instances: 1
  vm_type: ((environment))-prometheus-small
  persistent_disk_type: ((environment))-prometheus-small
  vm_extensions:
  - ((environment))-prometheus-lb
  stemcell: default
  azs: ((azs))
  networks:
  - name: ((environment))-monitoring
  jobs:
  - name: nginx
    release: prometheus
    properties:
      nginx:
        prometheus:
          http_port: 8081
          server_name: prometheus.((domain))
          headers: &security-headers
            X-Frame-Options: DENY
            X-Content-Type-Options: nosniff
            X-XSS-Protection: "1; mode=block"
            Strict-Transport-Security: "max-age=31536000; preload"
        alertmanager:
          http_port: 8081
          server_name: alertmanager.((domain))
          headers: *security-headers
        grafana:
          http_port: 8081
          server_name: grafana.((domain))
          headers: *security-headers
  - name: oauth2-proxy
    release: oauth2-proxy
    properties:
      address: http://0.0.0.0:8080
      upstream: http://127.0.0.1:8081
      provider: oidc
      client_id: ((oauth-proxy-client-id))
      client_secret: ((oauth-proxy-client-secret))
      cookie_secret: ((oauth-proxy-cookie-secret))
      oidc_issuer_url: https://opslogin.fr.cloud.gov/oauth/token
      email_domain: gsa.gov
variables:
- name: grafana-admin-password
  type: password
- name: oauth-proxy-client-secret
  type: password
- name: oauth-proxy-cookie-secret
  type: password
