name: prometheus-opensearch-((environment))

addons:
- include:
    stemcell:
    - os: ubuntu-jammy
  jobs:
  - name: bpm
    release: bpm
  name: bpm


releases:
- {name: prometheus, version: latest}
- {name: cron, version: latest}
- {name: bosh-dns-aliases, version: latest}
- {name: secureproxy, version: latest}
- {name: bpm, version: latest}

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-600000
  update_watch_time: 1000-600000
  serial: false

instance_groups:
- name: prometheus
  instances: 1
  vm_type: m6i.large
  persistent_disk_type: logs_opensearch_redis ##Change in future
  stemcell: default
  azs: ((azs))
  networks:
  - name: services # was environmnet-monitoring
  env:
    persistent_disk_fs: xfs
  jobs:
  - name: prometheus2
    release: prometheus
    properties:
      prometheus:
        storage:
          tsdb:
            retention:
              time: 365d
        web:
          external_url: https://prometheus.((domain))
        rule_files:
        - /var/vcap/jobs/bosh_alerts/*.alerts.yml
        - /var/vcap/jobs/cloudfoundry_alerts-attic/cf_cells.alerts.yml
        - /var/vcap/jobs/cloudfoundry_alerts-attic/cf_diego.alerts.yml
        - /var/vcap/jobs/cloudfoundry_alerts-attic/cf_doppler.alerts.yml
        - /var/vcap/jobs/cloudfoundry_alerts-attic/cf_routers.alerts.yml
        - /var/vcap/jobs/cloudfoundry_alerts-attic/prometheus_cf_exporter.alerts.yml
        - /var/vcap/jobs/prometheus_alerts/*.alerts.yml
        scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets:
            - localhost:9090
        - job_name: cf
          scrape_interval: 2m
          scrape_timeout: 100s
          static_configs:
          - targets:
            - localhost:9193
  - name: cf_exporter
    release: prometheus
    properties:
      bpm:
        enabled: true
      cf_exporter:
        cf:
          api_url: https://api.((domain))
          client_id: ((cf-exporter-client-id))
          client_secret: ((cf-exporter-client-secret))
          deployment_name: cf-((environment))
        metrics:
          environment: ((environment))
  - name: prometheus_alerts
    release: prometheus

- name: nginx
  instances: 1
  vm_type: t3.large
  persistent_disk_type: logs_opensearch_redis #((environment))-prometheus-small
  #vm_extensions:
  #- ((environment))-prometheus-lb
  stemcell: default
  azs: ((azs))
  networks:
  - name: services #((environment))-monitoring
  jobs:
  - name: nginx
    release: prometheus
    properties:
      nginx:
        prometheus:
          auth_users:
          - name: ((prometheus_user))
            password: ((promethues_password))
          http_port: 8082
          server_name: prometheus.((domain))
          headers: &security-headers
            X-Frame-Options: DENY
            Strict-Transport-Security: "max-age=31536000; preload"
  - name: secureproxy
    properties:
      secureproxy:
        listen_port: 8080
        proxy_port: 8081
    release: secureproxy
variables:
- name: promethues_password
  type: password
