# Scrape tooling prometheus via federation
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: federate
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
      - '{__name__=~"bosh_.*"}'
      - '{__name__=~"node_.*"}'
      - '{__name__=~"nessus_.*"}'
    static_configs:
    - targets:
      - 0.prometheus-tooling.production-monitoring.prometheus-production.toolingbosh:9090

# Add kubernetes broker exporter
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: kubernetes_broker_exporter
    scheme: https
    basic_auth:
      username: ((kubernetes-broker-exporter-username))
      password: ((kubernetes-broker-exporter-password))
    static_configs:
    - targets:
      - kubernetes-broker-exporter.app.cloud.gov:443

# Add tooling prometheus
- type: replace
  path: /instance_groups/-
  value:
    name: prometheus-tooling
    instances: 1
    vm_type: ((environment))-prometheus-large
    persistent_disk_type: ((environment))-prometheus-large
    stemcell: default
    azs: ((azs))
    networks:
    - name: ((environment))-monitoring
    env:
      persistent_disk_fs: xfs
    jobs:
    - name: prometheus
      release: prometheus
      properties:
        prometheus:
          external_labels:
            federate: prometheus-tooling
          scrape_configs:
          - job_name: prometheus
            static_configs:
            - targets:
              - localhost:9090
          - job_name: bosh
            scrape_interval: 1m
            scrape_timeout: 1m
            static_configs:
            - targets:
              - localhost:9190
          - job_name: node
            file_sd_configs:
            - files:
              - /var/vcap/store/bosh_exporter/bosh_target_groups.json
            relabel_configs:
            - source_labels: [__meta_bosh_job_process_name]
              regex: node_exporter
              action: keep
            - source_labels: [__address__]
              regex: "(.*)"
              target_label: __address__
              replacement: "${1}:9100"
    - name: bosh_exporter
      release: prometheus
      properties:
        bosh_exporter:
          bosh:
            url: ((tooling-bosh-url))
            ca_cert: ((bosh-ca-cert))
            uaa:
              url: ((tooling-bosh-url)):8443
              client_id: ((tooling-bosh-client-id))
              client_secret: ((tooling-bosh-client-secret))
          metrics:
            environment: tooling

# Disambiguate prometheus jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/provides?
  value:
    prometheus: {as: prometheus-primary}
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/consumes?
  value:
    prometheus: {from: prometheus-primary}
- type: replace
  path: /instance_groups/name=nginx/jobs/name=nginx/consumes?
  value:
    prometheus: {from: prometheus-primary}
