azs: [z1]
environment: production
domain: fr.cloud.gov
logsearch_file_size_threshold: 3000000
logsearch_log_count_threshold: 30000
logsearch_ratio_threshold: 50
blackbox-targets:
- https://dashboard.fr.cloud.gov
- https://login.fr.cloud.gov
- https://uaa.fr.cloud.gov
- https://api.fr.cloud.gov
- https://logs.fr.cloud.gov
- https://idp.fr.cloud.gov
- https://test-java.app.cloud.gov
- https://test-nodejs.app.cloud.gov
- https://test-dotnet-core.app.cloud.gov
- https://test-python-flask.app.cloud.gov
- https://test-php.app.cloud.gov
- https://test-ruby-padrino.app.cloud.gov
- https://test-ruby-sinatra.app.cloud.gov
- https://www.fec.gov
- https://api.data.gov
- https://fire.airnow.gov
- https://www.airnow.gov
- https://account.fr.cloud.gov
- https://cloud.gov
- https://ci.fr.cloud.gov
- https://opslogin.fr.cloud.gov
- https://doomsday.fr.cloud.gov
- https://pages-staging.cloud.gov
- https://pages.cloud.gov
- https://admin.pages-staging.cloud.gov
- https://admin.pages.cloud.gov
- https://test-cdn.fr.cloud.gov
