azs: [z2]
environment: staging
domain: fr-stage.cloud.gov
blackbox-targets:
- https://api.fr-stage.cloud.gov
- https://idp.fr-stage.cloud.gov
- https://login.fr-stage.cloud.gov
- https://uaa.fr-stage.cloud.gov
- https://logs.fr-stage.cloud.gov
- https://ci.fr-stage.cloud.gov
- https://dashboard.fr-stage.cloud.gov
- https://test-cdn.fr-stage.cloud.gov
opsgenie-url: https://api.opsgenie.com
